SELECT r.name,
    city_class(r.type) AS class,
    r.type AS type,
    ST_X(ST_PointOnSurface(ST_Transform(r.geometry, 4326))) AS lon,
    ST_Y(ST_PointOnSurface(ST_Transform(r.geometry, 4326))) AS lat,
    r.rank_search AS place_rank,
    getImportance(r.rank_search, r.wikipedia, r.calculated_country_code) AS importance,
    '' AS street,
    '' AS city,
    '' AS county,
    '' AS state,
    r.calculated_country_code AS country_code,
    countryName(r.partition) AS country,
    COALESCE(array_to_string(getHierarchyAsTextArray(r.parent_ids), ', ', '*'),'') AS display_name,  
    ST_XMIN(ST_Transform(r.geometry, 4326)) AS west,
    ST_YMIN(ST_Transform(r.geometry, 4326)) AS south,
    ST_XMAX(ST_Transform(r.geometry, 4326)) AS east,
    ST_YMAX(ST_Transform(r.geometry, 4326)) AS north
FROM osm_polygon AS r WHERE (r.name <> '') IS TRUE
UNION SELECT rr.name,
    city_class(rr.type) AS class,
    rr.type AS type,
    ST_X(ST_Transform(rr.geometry, 4326)) AS lon,
    ST_Y(ST_Transform(rr.geometry, 4326)) AS lat,
    rr.rank_search AS place_rank,
    getImportance(rr.rank_search, rr.wikipedia, rr.calculated_country_code) AS importance,
        '' AS street,
    '' AS city,
    '' AS county,
    '' AS state,
    rr.calculated_country_code AS country_code,
    countryName(rr.partition) AS country,
    COALESCE(array_to_string(getHierarchyAsTextArray(rr.parent_ids), ', ', '*'),'') AS display_name,  
    ST_XMIN(ST_Transform(rr.geometry, 4326)) AS west,
    ST_YMIN(ST_Transform(rr.geometry, 4326)) AS south,
    ST_XMAX(ST_Transform(rr.geometry, 4326)) AS east,
    ST_YMAX(ST_Transform(rr.geometry, 4326)) AS north
FROM osm_point AS rr WHERE (rr.name <> '') IS TRUE
UNION SELECT rrr.name,
    road_class(rrr.type) AS class,
    rrr.type,
    ST_X(ST_Line_Interpolate_Point(ST_Transform(rrr.geometry, 4326), 0.5)) AS lon,
    ST_Y(ST_Line_Interpolate_Point(ST_Transform(rrr.geometry, 4326), 0.5)) AS lat,
    rrr.rank_search AS place_rank,
    getImportance(rrr.rank_search, rrr.wikipedia, rrr.calculated_country_code) AS importance,
    rrr.name AS street,
    '' AS city,
    '' AS county,
    '' AS state,
    rrr.calculated_country_code AS country_code,
    countryName(rrr.partition) AS country,
    COALESCE(array_to_string(getHierarchyAsTextArray(rrr.parent_ids), ', ', '*'),'') AS display_name,  
    ST_XMIN(ST_Transform(rrr.geometry, 4326)) AS west,
    ST_YMIN(ST_Transform(rrr.geometry, 4326)) AS south,
    ST_XMAX(ST_Transform(rrr.geometry, 4326)) AS east,
    ST_YMAX(ST_Transform(rrr.geometry, 4326)) AS north
FROM osm_linestring AS rrr  WHERE (rrr.name <> '') IS TRUE
;