SELECT r.name,
    city_class(r.type) AS class,
    r.type AS type,
    ST_X(ST_PointOnSurface(ST_Transform(r.geometry, 4326))) AS lon,
    ST_Y(ST_PointOnSurface(ST_Transform(r.geometry, 4326))) AS lat,
    r.rank_search AS place_rank,
    0.75-(cast(r.rank_search as float)/40) AS importance,  
    '' AS street,
    '' AS city,
    '' AS county,
    COALESCE(placeName(r.state),'') AS state,
    COALESCE(countryCode(r.country),'') AS country_code,
    COALESCE(placeName(r.country),'') AS country,
    COALESCE(array_to_string(getHierarchyAsTextArray(r.parent_ids), ', ', '*'),'') AS display_name,  
    ST_XMIN(ST_Transform(r.geometry, 4326)) AS west,
    ST_YMIN(ST_Transform(r.geometry, 4326)) AS south,
    ST_XMAX(ST_Transform(r.geometry, 4326)) AS east,
    ST_YMAX(ST_Transform(r.geometry, 4326)) AS north
FROM osm_city_polygon AS r WHERE (r.name <> '') IS TRUE
UNION SELECT rr.name,
    city_class(rr.type) AS class,
    rr.type AS type,
    ST_X(ST_Transform(rr.geometry, 4326)) AS lon,
    ST_Y(ST_Transform(rr.geometry, 4326)) AS lat,
    rr.rank_search AS place_rank,
    0.75-(cast(rr.rank_search as float)/40) AS importance,  
        '' AS street,
    '' AS city,
    '' AS county,
    COALESCE(placeName(rr.state),'') AS state,
    COALESCE(countryCode(rr.country),'') AS country_code,
    COALESCE(placeName(rr.country),'') AS country,
    COALESCE(array_to_string(getHierarchyAsTextArray(rr.parent_ids), ', ', '*'),'') AS display_name,  
    ST_XMIN(ST_Transform(rr.geometry, 4326)) AS west,
    ST_YMIN(ST_Transform(rr.geometry, 4326)) AS south,
    ST_XMAX(ST_Transform(rr.geometry, 4326)) AS east,
    ST_YMAX(ST_Transform(rr.geometry, 4326)) AS north
FROM osm_city_point AS rr WHERE (rr.name <> '') IS TRUE
UNION SELECT rrr.name,
    road_class(rrr.type) AS class,
    rrr.type,
    ST_X(ST_Line_Interpolate_Point(ST_Transform(rrr.geometry, 4326), 0.5)) AS lon,
    ST_Y(ST_Line_Interpolate_Point(ST_Transform(rrr.geometry, 4326), 0.5)) AS lat,
    rrr.rank_search AS place_rank,
    0.75-(cast(rrr.rank_search as float)/40) AS importance, 
    rrr.name AS street,
    '' AS city,
    '' AS county,
    COALESCE(placeName(rrr.country),'') AS state,
    COALESCE(countryCode(rrr.country),'') AS country_code,
    COALESCE(placeName(rrr.country),'') AS country,
    COALESCE(array_to_string(getHierarchyAsTextArray(rrr.parent_ids), ', ', '*'),'') AS display_name,  
    ST_XMIN(ST_Transform(rrr.geometry, 4326)) AS west,
    ST_YMIN(ST_Transform(rrr.geometry, 4326)) AS south,
    ST_XMAX(ST_Transform(rrr.geometry, 4326)) AS east,
    ST_YMAX(ST_Transform(rrr.geometry, 4326)) AS north
FROM osm_road_linestring AS rrr  WHERE (rrr.name <> '') IS TRUE
;