FROM golang:1.7

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      libprotobuf-dev \
      libleveldb-dev \
      libgeos-dev \
      postgresql-client \
      --no-install-recommends \
 && ln -s /usr/lib/libgeos_c.so /usr/lib/libgeos.so \
 && rm -rf /var/lib/apt/lists/*

VOLUME /data
ENV IMPORT_DATA_DIR=/data/import

WORKDIR /usr/src/app
COPY . /usr/src/app
CMD ["./import-wikipedia.sh"]
