CLUSTER osm_linestring_geometry_center ON osm_linestring;
CLUSTER osm_polygon_geometry ON osm_polygon;
CLUSTER osm_housenumber_geometry_center ON osm_housenumber;
CLUSTER osm_point_geom ON osm_point;
